set nocompatible

filetype off

"tabs
set tabstop=4
set expandtab
set autoindent
set shiftwidth=4

"turn on highlighting
syntax on

"let those plugins load
filetype plugin indent on

"make backspace work normally
set backspace=indent,eol,start

"nombres
set number

"enter clears search highlight
noremap <enter> :noh<cr><cr>:<backspace>

"colorscheme
if has('termguicolors')
    set termguicolors
end

"mouse
set mouse=a

"spacebar as colon
noremap <space> :

set updatetime=300

"allow multiple buffers
set hidden

"status line
set noruler
set laststatus=2
set statusline=%n\ %f\ (%Y)\ %m\ %=\ %l/%L

" disable shift-up and shift-down as pgup and pgdn
noremap <S-Up> <Up>
noremap <S-Down> <Down>

set autochdir

set showbreak=-->\ 
set breakindent
set linebreak
hi NonText guifg=red guibg=None
