set nocompatible

filetype off

"set up vim plug
call plug#begin('~/.vim/plugged')

Plug 'chriskempson/base16-vim'

Plug 'tpope/vim-fugitive'

Plug 'machakann/vim-highlightedyank'

Plug 'neovim/nvim-lspconfig'

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'nvim-treesitter/nvim-treesitter'
Plug 'romgrk/nvim-treesitter-context'

call plug#end()

"tabs
set tabstop=4
set expandtab
set autoindent
set shiftwidth=4

"turn on highlighting
syntax on

"let those plugins load
filetype plugin indent on

"make backspace work normally
set backspace=indent,eol,start

"nombres
set number

"enter clears search highlight
noremap <enter> :noh<cr><cr>:<backspace>

"colorscheme
colorscheme base16-google-dark
if has('termguicolors')
    set termguicolors
end

"mouse
set mouse=a

"spacebar as colon
noremap <space> :

set updatetime=300

"allow multiple buffers
set hidden

"status line
set noruler
set laststatus=2
set statusline=%n\ %f\ (%Y)\ %m\ %=\ %l/%L

"C-w does window moves in terminal mode
tnoremap <C-w> <C-\><C-n><C-w>

"Don't print line numbers in terminal
autocmd TermOpen * setlocal nonumber norelativenumber

" set up completion
function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<Tab>" :
            \ coc#refresh()

inoremap <silent><expr> <S-Tab>
            \ pumvisible() ? "\<C-p>" :
            \ <SID>check_back_space() ? "\<S-Tab>" :
            \ coc#refresh()

" disable shift-up and shift-down as pgup and pgdn
noremap <S-Up> <Up>
noremap <S-Down> <Down>

set autochdir

set showbreak=-->\ 
set breakindent
set linebreak
hi NonText guifg=red guibg=None
