# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle :compinstall filename '/home/jeff/.zshrc'

autoload -Uz compinit promptinit
compinit
# End of lines added by compinstall

# makes all sessions share a history
setopt appendhistory # no overwriting
setopt sharehistory # share histories
setopt incappendhistory # add to history as commands run, not just at close

source ~/.commonprofile

plugins=(virtualenv)

function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}

autoload -Uz promptinit
promptinit

random_prompt_colour () {
    hostname_colour="yellow"
    prompt_colour_options=("red", "blue", "yellow", "green", "magenta")
    slashes=${$(pwd)//[^\\\/]/}
    dir_number=${#slashes}
    ((index=($dir_number % $#prompt_colour_options) + 1))

    if [[ "$TERM" != "dumb" ]]; then
        PS1="%B%(?..[%?] )%b%n@%F{$hostname_colour}%m%f> "
        RPS1="%F{$prompt_colour_options[$index]}%~%f"
    else
        PS1="%(?..[%?] )%n@%m:%~> "
    fi

    PROMPT=$(virtualenv_info)$PROMPT
}

term_title () {
    print -Pn "\e]2;%M:%~\a"
}

add-zsh-hook precmd random_prompt_colour
add-zsh-hook precmd term_title

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char

bindkey '^R' history-incremental-search-backward

alias sudo='sudo '

alias vi='nvim'
alias vim='nvim'

alias ..="cd .."
alias ...="cd ../.."

alias ls="ls -F"

alias ssh='TERM="xterm-256color" ssh'

alias svi='sudoedit'
alias svim='sudoedit'

set -k #comments in interactive mode

if [ -n "${NVIM+x}" ]; then
    alias h='nvr -o'
    alias v='nvr -O'
    alias vi='nvr -l'
fi

export EDITOR="nvim";

export PATH=/opt/oss-cad-suite/bin/:$PATH

