set nocompatible

filetype off

"set up vim plug
call plug#begin('~/.vim/plugged')

Plug 'vhda/verilog_systemverilog.vim' , { 'for' : [ 'verilog', 'systemverilog', 'verilogsystemverilog', 'verilog_systemverilog'] }

Plug 'lervag/vimtex', { 'for' : [ 'plaintex', 'tex' ] }

Plug 'ncm2/ncm2'

Plug 'chriskempson/base16-vim'

Plug 'ervandew/supertab'

Plug 'tpope/vim-fugitive'

Plug 'autozimu/LanguageClient-neovim', {
            \ 'branch' : 'next',
            \ 'do' : 'bash install.sh',
            \ }

Plug 'roxma/nvim-yarp'

Plug 'jiangmiao/auto-pairs'

Plug 'JuliaEditorSupport/julia-vim'

Plug 'jceb/vim-orgmode'

Plug 'tpope/vim-speeddating'

call plug#end()

"matching
runtime macros/matchit.vim

"tabs
set tabstop=4
set expandtab
set autoindent
set shiftwidth=4

"turn on highlighting
syntax on

"let those plugins load
filetype plugin indent on

"make backspace work normally
set backspace=indent,eol,start

"nombres
set number

"enter clears search highlight
noremap <enter> :noh<cr><cr>:<backspace>

"colorscheme
colorscheme base16-google-dark
if has('termguicolors')
    set termguicolors
end

"mouse
set mouse=a

"spacebar as colon
noremap <space> :

"tab completion with LSPs
autocmd BufEnter * call ncm2#enable_for_buffer()

set completeopt=noinsert,menuone,noselect

let g:LanguageClient_serverCommands = {
    \ 'python' : ['/usr/local/bin/pyls'],
    \ 'c' : ['/usr/bin/clangd']
    \ }

noremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>

"vimtex
let g:vimtex_view_method = "zathura"

"allow multiple buffers
set hidden

"status line
set noruler
set laststatus=2
set statusline=%n\ %f\ (%Y)\ %m\ %=\ %l/%L
