set nocompatible

filetype off

"set up vim plug
call plug#begin('~/.vim/plugged')

Plug 'vhda/verilog_systemverilog.vim' , { 'for' : [ 'verilog', 'systemverilog'] }

Plug 'lervag/vimtex', { 'for' : [ 'plaintex', 'tex' ] }

Plug 'ervandew/supertab'

Plug 'chriskempson/base16-vim'

call plug#end()

"tabs
set tabstop=4
set expandtab
set smartindent
set shiftwidth=4

"turn on highlighting
syntax on

"let those plugins load
filetype plugin indent on

"make backspace work normally
set backspace=indent,eol,start

"nombres
set number

"colorscheme
colorscheme base16-google-dark
if has('termguicolors')
    set termguicolors
end

"mouse
set mouse=a

"spacebar as colon
noremap <space> :

"supertab
let g:SuperTabDefaultCompletiontype = "context"

"vimtex
let g:vimtex_view_method = "zathura"

"allow multiple buffers
set hidden

"status line
set noruler
set laststatus=2
set statusline=%n\ %f\ (%Y)\ %m\ %=\ %l/%L
