set nocompatible

filetype off

"set up vim plug
call plug#begin('~/.vim/plugged')

Plug 'vhda/verilog_systemverilog.vim' , { 'for' : [ 'verilog', 'systemverilog', 'verilogsystemverilog', 'verilog_systemverilog'] }

Plug 'lervag/vimtex', { 'for' : [ 'plaintex', 'tex' ] }

Plug 'chriskempson/base16-vim'

Plug 'tpope/vim-fugitive'

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'roxma/nvim-yarp'

Plug 'JuliaEditorSupport/julia-vim', { 'for' : [ 'julia' ] }

Plug 'machakann/vim-highlightedyank'

call plug#end()

"tabs
set tabstop=4
set expandtab
set autoindent
set shiftwidth=4

"turn on highlighting
syntax on

"let those plugins load
filetype plugin indent on

"make backspace work normally
set backspace=indent,eol,start

"nombres
set number

"enter clears search highlight
noremap <enter> :noh<cr><cr>:<backspace>

"colorscheme
colorscheme base16-google-dark
if has('termguicolors')
    set termguicolors
end

"mouse
set mouse=a

"spacebar as colon
noremap <space> :

set updatetime=300

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~# '\s'
endfunction

inoremap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ coc#refresh()

inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

"let g:coc_snippet_next = '<Tab>'
"let g:coc_snippet_prev = '<S-Tab>'

inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gi <Plug>(coc-implementation)


"vimtex
let g:vimtex_fold_enabled = 1
let g:vimtex_view_method = "zathura"
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-shell-escape',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \ 'build_dir' : 'build',
    \}

let g:vimtex_quickfix_open_on_warning = 0

let g:tex_no_error=1

"allow multiple buffers
set hidden

"status line
set noruler
set laststatus=2
set statusline=%n\ %f\ (%Y)\ %m\ %=\ %l/%L

"wrap lines when writing latex
autocmd FileType tex setlocal textwidth=80

"C-w does window moves in terminal mode
tnoremap <C-w> <C-\><C-n><C-w>

"Don't print line numbers in terminal
autocmd TermOpen * setlocal nonumber norelativenumber

""control for basic movements in insert mode
"inoremap <C-h> <Left>
"inoremap <C-j> <Down>
"inoremap <C-k> <Up>
"inoremap <C-l> <Right>
"inoremap <C-i> <Home>
"inoremap <C-o> <End>
"nnoremap <C-i> <Home>
"nnoremap <C-o> <End>
